spring:
    datasource:
        url: jdbc:mysql://localhost:3306/departament_db?useSSL=false
        username: root
        password: docker
    jpa:
        hibernate.ddl-auto: update
        generate-ddl: true
    hikari:
      connection-timeout: 20000
      minimum-idle: 1
      maximum-pool-size: 5
      idle-timeout: 10000
    jackson:
        property-naming-strategy: SNAKE_CASE
